CXX = g++
CXXFLAGS = -Wall

PROGRAMS = \
	MulticastReceiver MulticastSender \
	MulticastReceiver6 MulticastSender6 \
	RcvBuf_TCPServer \
	RcvTimeO_UDPServer RcvTimeO_UDPClient \
	TCPServer UDPServer

all: $(PROGRAMS)

clean:
	rm -f $(PROGRAMS)
