CXX = g++
CXXFLAGS = -Wall

PROGRAMS = \
	TCPServer_Fixed TCPClient_Fixed \
	TCPServer_FixedVariable TCPClient_FixedVariable \
	TCPServer_Variable TCPClient_Variable \
	TCPServer_CloseOnTransfer TCPClient_CloseOnTransfer

all: $(PROGRAMS)

clean:
	rm -f $(PROGRAMS)
